class_name ModifierEnums
extends Node3D

enum TileModifierFlag {
	PROPERTY_COG = 1,
	CONDITION_ICY = 2,
	CONDITION_STICKY = 3,
	PROPERTY_CONVEYER = 4,
	PROPERTY_SPRINGY = 5,
	PROPERTY_WALL = 6,
	PROPERTY_POISON = 7,
	PROPERTY_KINGSFAVOR = 8,
	PROPERTY_GATE = 9,
	PROPERTY_BUTTON = 10,
	PROPERTY_LEVER = 11,
}
